FROM node:20-alpine as builder
WORKDIR /app
COPY package*.json .
RUN npm ci 
COPY . .
RUN npm run build

FROM node:20-alpine as production
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
RUN npm cache clean --force


CMD [ "node", "dist/main.js"]